Account/urls.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.urls import path
from .views import MyPage, userDelete

# Create your views here.
app_name="Account"
urlpatterns = [
    path('myPage/',MyPage.as_view(), name = "mypage"),
    path('delete_success/', userDelete, name="delete_success"),
]

EmotionBoard/urls.py
from django.urls import path, include
from .views import MainView, post_diary, DiarySave, CalendarDetail, CalendarDetails, DiaryListDetail, diary_list_detail, DiaryList, calendar_list_detail, satistic
from django.conf import settings
from django.conf.urls.static import static
app_name="EmotionBoard"
urlpatterns = [
    # path('account/view',UserView.as_view(), name = "account_view" ),
    path('', MainView.as_view(),name="board_main"),
    # path('index/',IndexView.as_view(), name="index_view" ),
    path('post_diary/', post_diary, name="post_diary"),
    path('diary_save/', DiarySave.as_view()),
    path('Account/', include('Account.urls')),
    path('diary_list/', DiaryList.as_view(),name='diary_list'),
    path('diary_detail/<int:pk>/', DiaryListDetail.as_view(),name='diary_detail'),
    path('diary_details/<int:pk>/', diary_list_detail ,name='diary_details'),
    path('calendar_detail/<int:pk>/', CalendarDetail.as_view(),name='calendar_detail'),
    path('calendar_details/<int:pk>/', calendar_list_detail,name='calendar_details'),
    path('emotion_chart/', satistic, name = "statics")
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Team_Final_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import Cal_t, Index2, Index, RegisterPage, BoardPage, UserCreateView,test, UserCreateDoneTV,login_view, change_password
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', test,name="main"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/',login_view, name="login" ),
    path('register/', UserCreateView.as_view(), name="register"),
    path('register/done/', UserCreateDoneTV.as_view(), name = 'register_done'),
    path('board/',include('EmotionBoard.urls')),
    path('account/password_change', change_password, name="password_change"),
    path('Account/', include('Account.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EmotionBoard/forms.py
from django.forms import ModelForm
from .models import Diary, DiaryTemp
from django import forms

class PreviewFileWidght(forms.ClearableFileInput):
    # def render(self, name. val)
    pass

class DiaryForm(ModelForm):
    class Meta:
        model = Diary
        fields = ['diary_img']

EmotionBoard/views.py
from django.shortcuts import render, redirect
from django.urls import path
from django.views.generic import TemplateView,CreateView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Movie_Drama_Recommend, Genre_Category, Diary, DiaryTemp, Recommend_Youtube, Emotion_Category, ModelValidDataset, Dataset, UserSelectGenreForEmotion
from EmotionBoard.forms import DiaryForm
from datetime import datetime, timedelta, date
from scripts.process import predictSenti
from django.contrib.auth import logout
from django.utils.safestring import mark_safe
from .utils import Calendar
import calendar
from django.core.paginator import Paginator
from dateutil import relativedelta
# Create your views here.

emotion_dict = {
    "angry":['코미디','드라마','애니메이션','음악'],
    "terror":['모험','판타지','SF', '로맨스'],
    "sadness":['코미디','애니메이션','음악'],
    "loathing":['액션','모험','코미디','가족'],
    "shock":['코미디','드라마','애니메이션','음악'],
    "expect":['코미디','로맨스','SF'],
    "pleasure":['모험','드라마','판타지','SF'],
    "calmness":['코미디','가족','음악','애니메이션']
}

emotion_select_dict = {
    "1" : "angry",
    "2" : "terror",
    "3" : "sadness",
    "4" : "loathing",
    "5" : "shock",
    "6" : "expect",
    "7" : "pleasure",
    "8" : "calmness"
}

emotion_to_kor = {
    "angry" : "화남",
    "calmness" : "평온",
    "expect" : "기대",
    "loathing" : "혐오",
    "pleasure" : "기쁨",
    "sadness" : "슬픔",
    "shock" : "놀람",
    "terror" : "두려움",
}

genre_list = ['모험','판타지','애니메이션','드라마','액션','코미디','SF','음악','로맨스','가족','TV 영화']

def genre_recommend(main_emotion):
    emotion_count = {}
    recommend_genre = []
    for i in UserSelectGenreForEmotion.objects.filter(emotion = Emotion_Category.objects.get(name = main_emotion)).all():
        for j in i.genre.all():
            if emotion_count.get(j.name) == None:
                emotion_count[j.name] = 1
            else:
                emotion_count[j.name] += 1

    
    for key, value in sorted(emotion_count.items(), key = lambda item:item[1], reverse=True):
        recommend_genre.append(key)
        if len(recommend_genre) == 3:
            break
    return recommend_genre

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()    
    
class CalendarView(TemplateView):
    model = Diary
    template_name = 'EmotionBoard/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None),)
        cal = Calendar(d.year, d.month, user=self.request.user)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context
    
#캘린더에서 이모티콘 클릭했을 때 나오는 일기 부분
class CalendarDetail(DetailView):
    model = Diary
    template_name ="EmotionBoard/calendar_detail.html"
    
    def get_context_data(self, **kwargs):       
        context = super(CalendarDetail,self).get_context_data()
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month, user=self.request.user)
        html_cal = cal.formatmonth(withyear=True)
        
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        
        return context

#캘린더에서 이모티콘 누르고 그 일기에서 상세 페이지 넘어갈 때 나오는 부분
class CalendarDetails(DetailView):
    model = Diary
    template_name ="EmotionBoard/calendar_details.html"
    
    def get_context_data(self, **kwargs):       
        context = super(CalendarDetails,self).get_context_data()
        print(Diary.objects.get(pk = self.kwargs['pk'])) #이렇게 해서 DetailView에서도 해당 pk값을 이용해 값을 뽑을 수 있음.
        user_select_emotion = Diary.objects.get(pk = self.kwargs['pk']).user_select_emotion
        print(Emotion_Category.objects.get(name = user_select_emotion).pk)
        context["youtube_list"] = Recommend_Youtube.objects.filter(emotion_id = Emotion_Category.objects.get(name = user_select_emotion).pk).order_by("?")[:10]
        print(context["youtube_list"])
        context['data'] = ['angry', 'calmness', 'expect', 'loathing', 'pleasure', 'sadness', 'shock', 'terror']

        return context
    

def calendar_list_detail(request, pk):
    print(pk)
    context = None
    main_emotion = Diary.objects.get(pk = pk).user_select_emotion.name
    data = ['angry', 'calmness', 'expect', 'loathing', 'pleasure', 'sadness', 'shock', 'terror']
    angry_percent = Diary.objects.get(pk=pk).angry_percent
    calmness_percent = Diary.objects.get(pk=pk).calmness_percent
    expect_percent = Diary.objects.get(pk=pk).expect_percent
    loathing_percent = Diary.objects.get(pk=pk).loathing_percent
    pleasure_percent = Diary.objects.get(pk=pk).pleasure_percent
    sadness_percent = Diary.objects.get(pk=pk).sadness_percent
    shock_percent = Diary.objects.get(pk=pk).shock_percent
    terror_percent = Diary.objects.get(pk=pk).terror_percent
    get_emotion_image = Emotion_Category.objects.get(name = Diary.objects.get(pk=pk).user_select_emotion).emotion_image.url
    youtube_list = Recommend_Youtube.objects.filter(emotion_id = Emotion_Category.objects.get(name = main_emotion).pk).order_by("?")[:10]
    print(main_emotion)
    print(emotion_dict.get(main_emotion))
    print(UserSelectGenreForEmotion.objects.filter(emotion = Emotion_Category.objects.get(name = main_emotion)).all())
    emotion_count = {}
    for i in UserSelectGenreForEmotion.objects.filter(emotion = Emotion_Category.objects.get(name = main_emotion)).all():
        for j in i.genre.all():
            print(j.name)
            if emotion_count.get(j.name) == None:
                emotion_count[j.name] = 1
            else:
                emotion_count[j.name] = emotion_count[j.name]+1
    print(sorted(emotion_count.items(), key = lambda item:item[1], reverse=True))
    recommend_genre = []
    for key, value in sorted(emotion_count.items(), key = lambda item:item[1], reverse=True):
        recommend_genre.append(key)
        if len(recommend_genre) == 3:
            break
    context = {
        "main_emotion" : main_emotion,
        "data" : emotion_to_kor.values(),
        "angry_percent" : angry_percent,
        "calmness_percent": calmness_percent,
        "expect_percent" : expect_percent,
        "loathing_percent" : loathing_percent,
        "pleasure_percent" : pleasure_percent,
        "sadness_percent" : sadness_percent,
        "shock_percent" : shock_percent,
        "terror_percent" : terror_percent,
        "get_emotion_image" : get_emotion_image,
        "youtube_list" : youtube_list,
        "genre_list" : genre_list,
        "movie_genre_list" : genre_recommend(main_emotion)
    }
    if request.method == "POST":
        print("selected : ",request.POST.getlist('selected'))
        genre_select_list = request.POST.getlist('selected')

        
        movie_drama_recommend_list = []
        for i in genre_select_list:
            movie_drama_recommend_list.append(Movie_Drama_Recommend.objects.filter(genre__name__startswith=i).order_by("?")[:5].values())
        context["recomment_list"] = movie_drama_recommend_list
        context["selected_list"] = genre_select_list
    return render(request, "EmotionBoard/diary_details.html", context=context)



class MainView(LoginRequiredMixin, UserPassesTestMixin, CalendarView):
    template_name = 'EmotionBoard/mainPage.html'
    
    def test_func(self):
        print(self.request.user)
        return self.request.user.is_superuser or self.request.user.is_staff or self.request.user.is_authenticated
    
    def get_context_data(self, **kwargs):
        context = super(MainView,self).get_context_data()
        #print(Diary.objects.filter(author = self.request.user).order_by("-write_date","-pk")[0])
        #print(datetime.today().day)
        if Diary.objects.filter(author = self.request.user).count() == 0:
            pass
        elif Diary.objects.filter(author = self.request.user).order_by("-write_date")[0].write_date.day < datetime.today().day:
            print("오늘 일기 없음")
        else:
            context['diary_title'] = Diary.objects.filter(author = self.request.user).order_by("-write_date","-pk")[0].diary_title
            context['diary_image'] = Diary.objects.filter(author = self.request.user).order_by("-write_date","-pk")[0].diary_img
            context['diary_content'] = Diary.objects.filter(author = self.request.user).order_by("-write_date","-pk")[0].diary_content
        return context
        # context['diary'] = Diary.objects.filter(author = self.request.user).filter()
        
        
    
    
    
    # #해당 장르 영화 가져오는 코드
    # def get_context_data(self, **kwargs):
    #     context = super(MainView,self).get_context_data()
    #     context['categories'] = Movie_Drama_Recommend.objects.filter(genre__name__startswith="로맨스")
    #     print(context['categories'])
    #     return context
    

    
def post_diary(request):
    print(f"request : {request.POST}")
    if not request.user.is_authenticated:
        return redirect("/board/")
    else:
        if request.POST:
            
            #일기 임시저장 버튼 눌렀을 시
            if request.method == "POST" and 'diary_temp' in request.POST:
                print(len(DiaryTemp.objects.filter(author = request.user)))
                response = DiaryTemp()
                print(request.FILES.get('image'))

EmotionBoard/templates/EmotionBoard/calendar.html
<div class="card">
    <div class="card-header">
        <a class="btn btn"  href="{{ calendar.get_main_url }}?{{ prev_month }}"> <<< </a>
         <span>calendar</span>
         <a class="btn btn" href="{{ calendar.get_main_url }}?{{ next_month }}"> >>> </a>
    </div>
    
    {{ calendar }}
    
</div>

EmotionBoard/templates/EmotionBoard/calendar_detail.html
{%extends 'EmotionBoard/board_base.html' %}
{%load static%}
{%block title%}
<title>Main Page</title>
{%endblock title%}
{%block content%}
    <body background="{%static 'css/images/layout/home10.png'%}"  style="overflow-x: hidden;  background-size: cover; background-repeat: no-repeat; image-rendering: crisp-edges; transform: translateZ(-); backface-visibility: hidden; height: 100%; width: 95%; text-align: center; margin: 0 auto; margin-right: 50px;" >
        
        <div class="row" >
            <div class="col-1 mt-5">
                <div class="mt-5">
                    <button id = "Home" class="mt-3" style="font-size: 15px; width: 150px; opacity:0;" onclick="Home()">Home</button>
                </div>
                <div class="mt-4">
                    <button class="mt-4" style="font-size: 15px; width: 150px; opacity:0;" onclick="Write_diary()">Home</button>
                </div>
                <div class="mt-4">
                    <button id = "Home" class="mt-4" style="font-size: 15px; width: 150px; opacity:0;" onclick="Diary_List()">Home</button>
                </div>
                <div class="mt-4">
                    <button class="mt-4" style="font-size: 15px; width: 150px; opacity:0;" onclick="MyPage()">Home</button>
                </div>
                <div class="mt-4">
                    <button class="mt-4" style="font-size: 15px; width: 150px; opacity:0;" onclick="EmotionChart()">Home</button>
                </div>
            </div>
            <div class="col-5 mt-5">
                <div class="mt-2">
                    {% include 'EmotionBoard/calendar.html' %}
                </div>
            </div>
            <!-- 해당 div 태그의 사이즈를 조절할 때 margin 0 auto 로 하고 width는 퍼센트. height는 padding-bottom %로 하면
            해당 %를 가진 div 박스가 완성된다 -->
            <div class="mt-5" style="height: 10%; width: 40%; margin: 0 auto; padding-right: 30px; padding-top: 30px;" >
                <div class="mt-2" >
                    <button class="btn btn-outline-secondary" onclick="location.href = '{{ diary.get_details_url }}'" style="position: absolute; margin-left: 240px; font-size: 25px; color: black;">상세보기</button>
                    <h1>{{ diary.write_date | date:'Y-m-d'}}</h1>
                <hr style="height: 1px; background: black;">
                <div style="overflow-y: scroll; height: 650px; padding-right: 20px;">
                    <div class="main_wrap">
                        <form name="write_diary_input" action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                                <div class="title_input clearfix" >
                                    <label for="inp" class="inp">
                                        <input type="title" name="title" id="inp" placeholder="&nbsp;" style="font-size: 15px; color: black;" value="{{diary.diary_title}}" readonly>
                                        
                                        <span class="label" style="font-size: 25px; text-align: center;">일기 제목</span>
                                        
                                        <span class="border"></span>
                                      </label>
                                      
                
                                    
                                </div>
                
                                <!-- <div class="filebox">
                                    <input class="upload-name" value="첨부파일" placeholder="첨부파일">
                                    <label for="file">파일찾기</label> 
                                    <input type="file" id="file">
                                </div> -->
                                <br>
                                <div class="write_diary_image_input" id = 'image_input' style="margin: auto;" >
                                    {% if  diary.diary_img %}
                                    <img src="{{ diary.diary_img.url }}" style=" image-rendering: -webkit-optimize-contrast ;width:98%; height:94%;">
                                    {% else %}
                                    <img src="" style=" image-rendering: -webkit-optimize-contrast ;height: 100%;">
                                    {% endif %}
                                </div>
                                <div style="margin-top: 10px;">
                                    
                                    
                                    <textarea class = "autosize"  id="text" name="content" style="height: 240px; overflow: visible; width: 80%;"onkeydown="resize(this)" readonly>{{ diary.diary_content }}</textarea>
                                    <br>
                                    <br>
                                    
                            
                            
                        </form>
                    </div>
                    
                    
                    
                </div>
                
            </div>
            </div>
        </div>
        
    </body>
    <!-- Bootstrap core JavaScript-->
    <script src="{%static 'vendor/jquery/jquery.min.js'%}"></script>
    <script src="{%static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{%static 'vendor/jquery-easing/jquery.easing.min.js'%}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{%static 'js/sb-admin-2.min.js'%}"></script>

    <!-- Page level plugins -->
    <script src="{%static 'vendor/chart.js/Chart.min.js'%}"></script>

    <!-- Page level custom scripts -->
    <script src="{%static 'js/demo/chart-area-demo.js'%}"></script>
    <script src="{%static 'js/demo/chart-pie-demo.js'%}"></script>
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"> -->
    
    <!-- calendar -->
    <link rel="stylesheet" href="{% static 'css/cal_styles.css' %}">
{%endblock content%}
{%block script%}
<script>
    function Home(){
        location.href = "{%url 'EmotionBoard:board_main'%}"
    }
    function Diary_List(){
        location.href = "{%url 'EmotionBoard:diary_list'%}"
    }

    function Write_diary(){
        location.href = "{%url 'EmotionBoard:post_diary'%}"
    }

    function MyPage(){
        location.href = "{%url 'Account:mypage'%}"
    }

    function EmotionChart(){
        location.href = "{%url 'EmotionBoard:statics'%}"
    }

</script>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/event_style.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!-- calendar -->
<link rel="stylesheet" href="{% static 'css/cal_styles.css' %}">
{%endblock script%}

EmotionBoard/templates/EmotionBoard/mainPage.html
{%extends 'EmotionBoard/board_base.html' %}
{%load static%}
{%block title%}
<title>Main Page</title>
{%endblock title%}
{%block content%}
    <body background="{%static 'css/images/layout/home10.png'%}"  style="background-repeat: no-repeat; image-rendering: crisp-edges; transform: translateZ(-); backface-visibility: hidden; height: 100%; width: 95%; text-align: center; margin: 0 auto; margin-right: 50px;" >
        
        <div class="row" >
            <div class="col-1 mt-5">
                <div class="mt-5">
                    <button id = "Home" class="mt-3" style="font-size: 15px; width: 150px; opacity:0;" onclick="Home()">Home</button>
                </div>
                <div class="mt-4">
                    <button class="mt-4" style="font-size: 15px; width: 150px; opacity:0;" onclick="Write_diary()">Home</button>
                </div>
                <div class="mt-4">
                    <button id = "Home" class="mt-4" style="font-size: 15px; width: 150px; opacity:0;" onclick="Diary_List()">Home</button>
                </div>
                <div class="mt-4">
                    <button class="mt-4" style="font-size: 15px; width: 150px; opacity:0;" onclick="MyPage()">Home</button>
                </div>
                <div class="mt-4">
                    <button class="mt-4" style="font-size: 15px; width: 150px; opacity:0;" onclick="EmotionChart()">Home</button>
                </div>
            </div>
            <div class="col-5 mt-5">
                <div class="mt-3">
                    {% include 'EmotionBoard/calendar.html' %}
                </div>
            </div>
            <!-- 해당 div 태그의 사이즈를 조절할 때 margin 0 auto 로 하고 width는 퍼센트. height는 padding-bottom %로 하면
            해당 %를 가진 div 박스가 완성된다 -->
            <div class="mt-5" style="height: 10%; width: 40%; margin: 0 auto; padding-right: 30px; padding-top: 30px;" >
                <div class="mt-2" >
                    <h1 id = "current_date"></h1>
                    <hr style="height: 1px; background: black;">
                    <div style="height: 700px;">
                        {%if diary_title%}
                        <div class="main_wrap" style="margin-top: 20px;">
                            <form name="write_diary_input" action="" method="POST" enctype="multipart/form-data">
                                <div class="title_input clearfix" style="text-align: center; margin-top: 30px;">
                                    <label for="inp" class="inp">
                                        {%if diary_title%}
                                        <input type="title" name="title" id="inp" placeholder="&nbsp;" style="font-size: 25px;"
                                            value="{{diary_title}}" readonly>
                                        {%else%}
                                        <input type="title" name="title" id="inp" placeholder="&nbsp;" style="font-size: 25px;">
                                        {%endif%}
                                        <span class="label" style="font-size: 20px;">일기 제목</span>
                                        <span class="border"></span>
                                    </label>
        
        
                                </div>
                                
                                <div class="write_diary_image_input" id='image_input' style="margin: auto; margin-top: 30px;">
                                    {%if diary_image%}
                                    <img src="{{diary_image.url}}"
                                        style="width:98%; height:94%; image-rendering: -webkit-optimize-contrast;">
                                    {%else%}
        
                                    {%endif%}
                                </div>
                                <div style="text-align: center; margin-top: 40px;">
                                    {% csrf_token %}
        
                                    <textarea placeholder="일기 내용" id="text" name="content"
                                        style="height: 250px; width: 90%; overflow: visible; margin-bottom: 20px;"
                                        onkeydown="resize(this)" readonly>{{diary_content}}
                                        </textarea>
                                </div>
        
                        </div>
                        {%else%}
                        <br>
                        <h1 style="color: black; font-weight: bold;">오늘 작성된 일기가 없어요</h1>
                        <h2 style="color: black;">일기를 작성하러 가요!</h2>
                        <br>
                        <br>
                        
        

                        <br>
                        <br>
                        <br>
                        <br>
                        <br>

                        <button type="button" class="btn btn-outline-secondary" style="font-size: 25px;" onclick="Write_diary()">일기 작성하기</button>
                        {%endif%}
                    </div>
                </div>
            </div>
        </div>
        
    </body>
    <!-- Bootstrap core JavaScript-->
    <!-- <script src="{%static 'vendor/jquery/jquery.min.js'%}"></script>
    <script src="{%static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script> -->

    <!-- Core plugin JavaScript-->
    <!-- <script src="{%static 'vendor/jquery-easing/jquery.easing.min.js'%}"></script> -->

    <!-- Custom scripts for all pages-->
    <!-- <script src="{%static 'js/sb-admin-2.min.js'%}"></script> -->

    <!-- Page level plugins -->
    <!-- <script src="{%static 'vendor/chart.js/Chart.min.js'%}"></script> -->

    <!-- Page level custom scripts -->
    <!-- <script src="{%static 'js/demo/chart-area-demo.js'%}"></script>
    <script src="{%static 'js/demo/chart-pie-demo.js'%}"></script> -->
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/event_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/cal_styles.css' %}">
{%endblock content%}
{%block script%}
<script>
    function Home(){
        location.href = "{%url 'EmotionBoard:board_main'%}"
    }
    function Write_diary(){
        location.href = "{%url 'EmotionBoard:post_diary'%}"
    }

    function Diary_List(){
        location.href = "{%url 'EmotionBoard:diary_list'%}"
    }

    function MyPage(){
        location.href = "{%url 'Account:mypage'%}"
    }

    function EmotionChart(){
        location.href = "{%url 'EmotionBoard:statics'%}"
    }
</script>
<script>
    date = new Date();
    year = date.getFullYear();
    month = date.getMonth() + 1;
    day = date.getDate();
    document.getElementById("current_date").innerHTML = year + "년 " + month + "월 " + day + "일";
</script>
{%endblock script%}